# Site wide configuration

title: Fabian Schuhmann
locale: de_DE
logo: logo.jpg

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Fabian Schuhmann
  avatar: Bild_Uol.jpg
  bio: "Niels Bohr Institute, University of Copenhagen"
  email: fabian.schuhmann@nbi.ku.dk
  # Do not include the @ symbol in your Twitter username
  twitter: fabianschuhmann
  linkedin: fabian-schuhmann-10135a193
  github: fabianschuhmann
  orcid: 0000-0002-3768-6494 
  researchgate: "Fabian Schuhmann"
  mendeley: #username
  google:
    plus: #username
    analytics:
    verify:
    scholar: #id
  facebook: #username
  instagram: #username
  bing-verify:
  stackoverflow: #123456/username from a "https://stackoverflow.com/users/123456/username" link
  xing: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  disqus-shortname:

# The following adjust the accents for your site. If you would like to further edit colors, fonts, font sizes, etc.
# you may do so in _sass/variables.scss
highlight-color: '#003366'
lowlight-color: '#000'

  # NOTE: If you would like your site to be licensed under a creative commons license, uncomment the 'yes' next to the type of license you wish to use.
creative-commons:
  cc-by: #yes
  cc-by-nc: yes

#DO NOT EDIT BEYOND THIS POINT
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-twitter-plugin

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

FOLDER: dist
BUILD_SCRIPT: mkdir dist && mv src/* dist
